name: Send email
on:
  push:
    branches:
      - main
jobs:
  sending-email:
    name: correo
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Message from github actions.
          to: rcruzortiz@outlook.com
          from: Git Hub
          secure: true
          body: workflow for ${{github.repository}} completed successfully!
